name: pagila_gold
profile: pagila
version: "1.0.0"
config-version: 2
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: # dbt clean
  - "target"
  - "logs"
  - "dbt_packages"
packages-install-path: "dbt_packages"
models:
  pagila:
    marts:
      +materialized: table
flags:
  send_anonymous_usage_stats: False
